### ISSUE TITLE
Problem with CJMCU-811

### ISSUE THREAD

**Issue by GillesC** [AKstudios/CCS811-library#2]
Hello

First of all thank you for making this library!
I'm unable to get your test file working.

Connection:
**Loenardo**............................**CJMCU-811**
   3.3V......................................VCC
   GND.....................................GND
   GND.....................................ADD
   PIN_2...................................SDA
   PIN-3...................................SCL
   PIN_4...................................WAK
   PIN-7...................................INT

I get the following error:
`Error: Incorrect Hardware ID detected.`
I've written out the `hw_id` which is 0xFF.

Kind regards,
Gilles Callebaut

**Comment by AKstudios** [comment]
This happens when the timing sequence for initialization isn't correct. Try adding some more delay. Also, try power-cycling the chip.

**Comment by GillesC** [comment]
I'll give it a try. Thank you for your time!
I'll close this issue when the problem is resolved.

**Comment by AKstudios** [comment]
The example code in the library should work. Try switching to a 0.1uF cap and power cycle the circuit with sufficient time between each cycle (so cap is discharged).

Note that this a relatively new sensor, so it's possible there are some earlier finicky versions around in the market. It's also a bit tricky to get it reflowed correctly the first time since the pads are so small.

**Comment by arronstone** [comment]
@GillesC has it worked for you ?
Please share details if it worked, as i am also facing the same issue.

**Comment by GillesC** [comment]
Hey,
I haven't got the time to resolve this issue. I tried to increase some
delays but without success.

**Comment by AKstudios** [comment]
The library has been updated; should allow more time before first communication.

**Comment by a-andreyev** [comment]
tried today with `CJMCU-811`, working for me

**Comment by madhujiot** [comment]
Today, I got from Aliexpress the CJMCU-811 module and am trying to configure and run the CCS811-library example given in this repository, but facing below issue. Please suggest what could be wrong and appreciate your help.

My connections for the Arduino to CJMCU-811
Arduino 	<-----> CJMCU-811
3.3V 	<-----> VCC
GND 	<-----> GDN
GND 	<-----> ADD
A4 		<-----> SDA
A5 		<-----> SCL
PIN_4(PWM) 	<-----> WAK
NA 		<-----> INT
NA 		<-----> RST

*NA = unused

COM port output(9600baud) per below:
----------------------------------
CCS811 test
Error: Incorrect Hardware ID detected.
Initialization failed.
CO2 concentration : 30720 ppm
TVOC concentration : -29344 ppb

CO2 concentration : 30720 ppm
TVOC concentration : -29344 ppb

CO2 concentration : 30720 ppm
TVOC concentration : -29344 ppb
-----------------------------------------------
Thank you,
Madhu

**Comment by coolchip** [comment]
I²C Address should be 0x5A or 0x5B. Perhaps this helps.
